// Type Definitions for DMX Website
// This file contains all TypeScript interfaces used throughout the application
// These types correspond to Firestore document structures

// Event interface - represents an event document in Firestore
// Collection: 'events'
export interface Event {
  id: string;                    // Document ID (auto-generated by Firestore)
  title: string;                 // Event title/name
  date: Date;                    // Event date (Firestore Timestamp)
  description: string;           // Event description/details
  coverImage: string;            // URL to event cover image (Firebase Storage)
  speakers?: string[];           // Optional array of speaker names
  venue?: string;                // Optional venue location
  mdxSlug: string;              // Slug for MDX content (for Fumadocs integration)
  registrationLink?: string;     // Optional registration/RSVP link
}

// Project interface - represents a project document in Firestore
// Collection: 'projects'
export interface Project {
  id: string;                    // Document ID (auto-generated by Firestore)
  title: string;                 // Project title/name
  description: string;           // Project description
  techStack: string[];           // Array of technologies used
  githubLink?: string;           // Optional GitHub repository URL
  demoLink?: string;             // Optional live demo URL
  coverImage?: string;           // Optional project cover image URL
  featured: boolean;             // Whether to show on homepage as featured
}

// Team Member interface - represents a team member document in Firestore
// Collection: 'team'
export interface TeamMember {
  id: string;                    // Document ID (auto-generated by Firestore)
  name: string;                  // Member's full name
  role: string;                  // Member's role/position in the team
  photoUrl: string;              // URL to member's profile photo
  bio?: string;                  // Optional biography/description
  socialLinks: {                 // Social media links object
    github?: string;             // Optional GitHub profile URL
    linkedin?: string;           // Optional LinkedIn profile URL
    twitter?: string;            // Optional Twitter profile URL
  };
  year: number;                  // Academic year or graduation year
}
